---
## Author
author:
  name: Постнова Елизавета Андреевна
  email: 1132236051@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      city: Москва
      address: ул. Орджоникидзе, д. 3

## Title
title: "Отчёт по лабораторной работе №3"
subtitle: "Агентное моделирование"
---

# Цель работы

Цель данной лабораторной работы - исследовать агентное моделирование на примере модели Daisyworld.

# Задание

— Создать рабочий каталог для всего курса.
— Установить необходимые пакеты.
— Выполнить предложенный код.
— Преобразовать код в литературный стиль.
— Сгенерировать из литературного кода:
— чистый код;
— jupyter notebook;
— документацию в формате Quarto.
— Выполнить код из jupyter notebook.
— Интегрировать документацию в формате Quarto в отчёт.
— Добавить в код в литературном стиле вычисление для набора параметров.
— Сгенерировать из литературного кода с параметрами:
— чистый код;
— jupyter notebook;
— документацию в формате Quarto.
— Выполнить код из jupyter notebook с параметрами.
— Интегрировать документацию с параметрами в формате Quarto в отчёт.
— Результирующие файлы не удаляйте, выложите на git.

[@simulatiom_modeling].

# Выполнение лабораторной работы

##  Агентный подход

Агентный подход к имитационному моделированию (Agent-Based Modeling, ABM)
— это метод исследования сложных систем, в котором поведение системы возникает из взаимодействия множества автономных сущностей, называемых агентами.
Вместо того чтобы описывать систему глобальными уравнениями, мы моделируем каждую индивидуальную единицу и правила её поведения, а затем наблюдаем,
какие коллективные паттерны появляются снизу вверх. Этот подход особенно
полезен, когда поведение системы трудно предсказать из-за нелинейностей, гетерогенности участников или адаптивных стратегий.

### Этапы построения агентной модели

— Концептуализация: определить цель модели, выделить ключевых агентов, их
атрибуты и правила, описать среду и взаимодействия.

— Спецификация: формально описать модель (можно использовать псевдокод
или диаграммы).

— Реализация: написать код на выбранном языке.

— Верификация: проверить, что программа правильно реализует задуманные
правила (нет ошибок).

— Валидация: сравнить результаты модели с реальными данными или ожидаемым поведением, чтобы убедиться в адекватности модели.

— Анализ: провести эксперименты, варьируя параметры, изучить чувствительность, выявить закономерности.

— Интерпретация: связать полученные результаты с реальным миром или теоретическими концепциями.

## Модель Daisyworld

Модель Daisyworld, предложенная Джеймсом Лавлоком и Эндрю Уотсоном, иллюстрирует гипотезу Геи [@daisyworld; @homeostasis]. Гипотеза Геи рассматривает планету как единую,
саморегулирующуюся систему, включающую как живые, так и неживые части.
В мире маргариток произрастают чёрные и белые маргаритки. Их альбедо различается: чёрные маргаритки поглощают свет и тепло, нагревая окружающую
среду; белые маргаритки делают наоборот. Маргаритки могут размножаться только в определённом температурном диапазоне, а это значит, что слишком много
(или слишком мало) тепла от солнца и/или окружающей среды в конечном итоге
остановит их размножение.
Поверхность Геи нагревается солнцем, но растущие на ней маргаритки поглощают
или отражают свет звёзд, изменяя локальную температуру.
Если температура становится слишком высокой или слишком низкой, маргаритки
не захотят размножаться. Пока температура благоприятна, маргаритки конкурируют за землю и пытаются дать начало новому растению в местах, расположенных
неподалёку от них.
Когда климат слишком холодный, черным маргариткам необходимо размножаться, чтобы повысить температуру, и наоборот — когда климат слишком теплый,
необходимо производить больше белых маргариток, чтобы охладить климат.
Взаимодействие живых и неживых аспектов этого мира находит равновесие в
широком диапазоне параметров, хотя при достаточно сильном внешнем воздействии маргаритки не смогут регулировать температуру планеты и в конечном
итоге вымрут.

{{< include ../project/markdown/daisyworld/daisyworld.qmd >}}

{{< include ../project/markdown/daisyworld-count/daisyworld-count.qmd >}}

{{< include ../project/markdown/daisyworld-luminosity/daisyworld-luminosity.qmd >}}

{{< include ../project/markdown/daisyworld__param/daisyworld__param.qmd >}}

{{< include ../project/markdown/daisyworld-count__param/daisyworld-count__param.qmd >}}

{{< include ../project/markdown/daisyworld-luminosity__param/daisyworld-luminosity__param.qmd >}}

# Выводы

По итогам лабораторной работы был изучен агентный подход к имитационному моделированию, построена и иследованна с заданными параметрами модель Daisyworld.

# Список литературы{.unnumbered}

::: {#refs}
:::