---
## Author
author:
  name: Постнова Елизавета Андреевна
  email: 1132236051@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      city: Москва
      address: ул. Орджоникидзе, д. 3

## Title
title: "Отчёт по лабораторной работе №4"
subtitle: "Реализация основных моделей в агентном подходе"
date: today
date-format: "YYYY-MM-DD" # Example: 2025-09-06
---

# Информация

## Докладчик

:::::::::::::: {.columns align=center}
::: {.column width="70%"}

  * Постнова Елизавета Андреевна
  * Российский университет дружбы народов им. П. Лумумбы
  * [1132236051@rudn.ru](mailto:1132236051@rudn.ru)

:::
::: {.column width="30%"}

:::
::::::::::::::


# Вводная часть

## Актуальность темы

 Классические и фундаментальные математические модели всегда актуальны как основа имитационного моделирования.

## Объект и предмет исследования

- Модель SIR

- Агентный подход

## Практическая значимость работы

Изучение основных математических моделей необходимо для понимания работы моделей, в основу которых они легли.

## Цели и задачи

Цель данной лабораторной работы - исследовать основную математическую модель SIR в агентном подходе.

## Материалы и методы

- Язык Julia и его пакеты

- Agent.jl

- Результирующий формат`Jupiter Notebook`

# Модель SIR

Модель SIR есть классическая и фундаментальная математическая модель эпидемиологии, описывающая распространение инфекционного заболевания в закрытой популяции.

## Ключевая идея

##

Количественное описание динамики инфекционного заболевания в популяции. Реализация классической компартментальной модели SIR, разделяющей популяцию на три группы:

S (Susceptible) — восприимчивые к инфекции

I (Infected) — инфицированные

R (Recovered) — выздоровевшие (с иммунитетом)

## 

Оценка влияния параметров передачи инфекции на динамику эпидемического процесса:

$\beta$ (вероятность заражения при контакте)

$c$ (среднее число контактов)

$\gamma$ (скорость выздоровления) 

## Агенты

Каждый агент — человек, обладающий следующими свойствами:

— status::Symbol — состояние (:S, :I, :R);

— days_infected::Int — количество дней с момента заражения (для инфицированных).

## Пространство состояний

Агенты размещаются на графе, где узлы представляют локации (города, районы), а рёбра — возможные перемещения между ними. Такой подход позволяет
моделировать метапопуляционную динамику и миграцию

## Параметры модели

— Ns — вектор численности населения по локациям;

— β_und — вероятность передачи для невыявленных случаев;

— β_det — вероятность передачи для выявленных случаев;

— infection_period — длительность заболевания (дней);

— detection_time — время до выявления заболевания;

— death_rate — вероятность летального исхода;

— reinfection_probability — вероятность повторного заражения;

— migration_rates — матрица вероятностей миграции между локациями.


# Заключение и выводы

По итогам лабораторной работы была изучена, построена и иследованна с заданными параметрами основная математическая модель SIR.
