---
## Author
author:
  name: Постнова Елизавета Андреевна
  email: 1132236051@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      city: Москва
      address: ул. Орджоникидзе, д. 3

## Title
title: "Отчёт по лабораторной работе №2"
subtitle: "Основные модели"
---

# Цель работы

Цель данной лабораторной работы - исследовать основные математические модели --- SIR и Лотки-Вольтерры.

# Задание

— Создать рабочий каталог для всего курса.
— Установить необходимые пакеты.
— Выполнить предложенный код.
— Преобразовать код в литературный стиль.
— Сгенерировать из литературного кода:
— чистый код;
— jupyter notebook;
— документацию в формате Quarto.
— Выполнить код из jupyter notebook.
— Интегрировать документацию в формате Quarto в отчёт.
— Добавить в код в литературном стиле вычисление для набора параметров.
— Сгенерировать из литературного кода с параметрами:
— чистый код;
— jupyter notebook;
— документацию в формате Quarto.
— Выполнить код из jupyter notebook с параметрами.
— Интегрировать документацию с параметрами в формате Quarto в отчёт.

[@simulatiom_modeling].

# Выполнение лабораторной работы

##  Модель SIR

Модель SIR есть классическая и фундаментальная математическая модель эпидемиологии, описывающая распространение инфекционного заболевания в закрытой популяции [@the_mathematics_of_Infectious_diseases; @mathematical_theory_of_epidemics].

Модель SIR делит всю популяцию на три взаимосвязанные группы, что отражено в её названии:

— 𝑆 — Susceptible (Восприимчивые): люди, которые не болели, не имеют иммунитета и могут заразиться.

— 𝐼 — Infectious (Инфицированные/Заразные): люди, которые в данный момент
больны и могут передавать инфекцию.

— 𝑅 — Recovered (Выздоровевшие/Удаленные): люди, которые переболели и приобрели иммунитет (или умерли). Они больше не участвуют в процессе передачи.

Основная цель модели: не предсказать судьбу конкретного человека, а понять общую динамику эпидемии — будет ли она разрастаться, как быстро, сколько
людей в итоге переболеет, как влияют карантинные меры.

{{< include ../project/markdown/sir_ode/sir_ode.qmd >}}

## Модель Лотки–Вольтерры

Модель Лотки-Вольтерры — это фундаментальная математическая модель в экологии, описывающая динамику взаимодействия двух видов: хищников и жертв.

Она была независимо предложена в 1920-х годах:

— Альфредом Лоткой (1925) для химических реакций [@theory_of_periodic_reaction; @elements_of_physical_biology].


— Витторио Вольтеррой (1926) для объяснения колебаний улова рыбы в Адриатическом море [@animal_species_living_together; @mathematical_theory_of_fight].


Модель демонстрирует, как даже простая система взаимодействий может порождать сложные колебательные режимы, объясняя циклические изменения численности в природных экосистемах.

{{< include ../project/markdown/lv_ode/lv_ode.qmd >}}

# Выводы

По итогам лабораторной работы были изучены, построены и иследованны с заданными параметрами основные математические модели --- SIR и Лотки-Вольтерры.

# Список литературы{.unnumbered}

::: {#refs}
:::
